# Generated by Django 6.1.1 on 2026-09-29 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbtasks", "0002_scheduledtask_delete_after"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("backend", models.CharField(default="default", max_length=32)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="backend",
            field=models.CharField(default="default", max_length=32),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="dbtasks.worker",
            ),
        ),
    ]
